Repository s4u/setup-maven-action, pull requests merged in 2024-02, with the labels that each got.

#70 Update stCarolas/setup-maven to v5
  action.yml
Labels: dependencies

#72 Maven 3.9.6 as default
  .github/workflows/test.yml
  README.md
  action.yml
Labels: enhancement

#73 Fix misspell in test action
  .github/workflows/test.yml
Labels: code quality
